#!/usr/bin/perl -w

# Copyright (C) 2023 Mo Zhou <lumin@debian.org>
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
# .
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
# .
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

use strict;
use Debian::Debhelper::Dh_Lib;

my %data;

open(FILE, '<', '/usr/lib/python3/dist-packages/torch/version.py')
    or error("cannot read version info: $!\n");
while (<FILE>) {
    chomp;
    next unless /^[^#]/;
    my ($key, $eq, $value) = split;
    $value =~ s/['"]+//g;
    $data{$key} = $value;
}
close FILE;

if (not exists $data{__version__}) {
    error("cannot find __version__ field in the version file.")
}

my @array = split('\.', $data{__version__});

foreach my $package (@{$dh{DOPACKAGES}}) {
    my $pytorch_dep = "python3-torch | python3-torch-api-$array[0].$array[1]";
    addsubstvar($package, "python3:Depends", $pytorch_dep);
}

exit 0
